### ISSUE TITLE
Deal with activities that are planned whole day and months in Dutch language

### ISSUE THREAD

**Issue by evdalen** [toaomatis/AutoffOffice#5]
Your out of office flow is very nice. I like it. However I was thinking about some improvements. I am a newbie for making flows, so hopefully you can help me to further optimize your out of office flow.
If you add out of office activities for the whole day which end at 00:00 (or activities that end after working hours, i.e. 21:00), I would like to move my endTime to next day 8:00. So, I can notify the sender when I will be able to read his message. I know I could enter the out of office activities until next morning, but that's not what I prefer.
Another wish is to use the name of months in my message, but as you know you can only get the English names of the months. So would like to use a table to convert the number of the month to a name.

Thanks,
Edwin

**Comment by toaomatis** [comment]
Thanks for your suggestion, unfortunately I don't work at a company with Office365 anymore, so I can't develop on this Flow anymore. 

Will mark this repository as read only to not disappoint any other users and their feedback.
